In [1]:
import numpy as np
import pandas as pd

import mlcookbook

from sklearn.datasets import load_boston, load_breast_cancer

boston_data = load_boston()
data = pd.DataFrame(boston_data.data, columns=boston_data.feature_names)
data['Target'] = boston_data.target

breast_cancer_data = load_breast_cancer()
categorical_data = pd.DataFrame(breast_cancer_data.data, columns=breast_cancer_data.feature_names)
categorical_data['Target'] = breast_cancer_data.target

In [4]:
print('Percent Missing')
mlcookbook.eda.percent_missing(data)

Percent Missing Test
No missing values


## Outliers

In [7]:
print('IQR outliers')
mlcookbook.eda.iqr_indices_of_outliers(data.iloc[:, 0])

IQR outliers


(array([367, 371, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 384,
        385, 386, 387, 388, 392, 394, 398, 399, 400, 401, 402, 403, 404,
        405, 406, 407, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418,
        419, 420, 422, 425, 426, 427, 429, 431, 434, 435, 436, 437, 438,
        439, 440, 441, 443, 444, 445, 447, 448, 454, 468, 469, 477, 478,
        479], dtype=int64),)

In [9]:
print('Z score outliers')
mlcookbook.eda.z_score_indices_of_outliers(data.iloc[:, 0])

Z score outliers


(array([380, 398, 404, 405, 410, 414, 418, 427], dtype=int64),)

In [10]:
print('Percentile outliers')
mlcookbook.eda.percentile_indices_of_outliers(data.iloc[:, 0])

Percentile outliers


(array([  0, 284, 285, 380, 405, 418], dtype=int64),)

In [11]:
print('Ellipses outliers')
mlcookbook.eda.ellipses_indices_of_outliers(data)

Ellipses outliers


(array([367, 374, 375, 376, 378, 379, 380, 381, 384, 385, 386, 387, 388,
        392, 394, 398, 400, 401, 403, 404, 405, 406, 407, 409, 410, 411,
        412, 413, 414, 415, 416, 417, 418, 419, 422, 425, 426, 427, 434,
        435, 436, 437, 438, 440, 444, 445, 454, 468, 469, 477, 479],
       dtype=int64),)

In [12]:
print('Isolation Forest outliers')
mlcookbook.eda.isolation_forest_indices_of_outliers(data)

Isolation Forest outliers


(array([102, 141, 142, 143, 144, 145, 146, 147, 148, 152, 153, 155, 156,
        159, 161, 162, 163, 166, 195, 197, 204, 225, 253, 257, 258, 261,
        262, 263, 265, 267, 283, 353, 354, 355, 365, 367, 368, 380, 404,
        405, 410, 412, 414, 418, 419, 424, 426, 427, 438, 489, 490],
       dtype=int64),)

In [13]:
print('One class SVM outliers')
mlcookbook.eda.one_class_svm_indices_of_outliers(data)

One class SVM outliers


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


(array([  0,   2,   3,   5,   6,   7,   9,  10,  12,  13,  15,  16,  17,
         20,  21,  22,  25,  30,  31,  32,  33,  34,  35,  38,  39,  41,
         42,  43,  44,  48,  49,  50,  51,  53,  54,  55,  56,  63,  68,
         73,  75,  76,  79,  81,  89,  93,  94,  97,  99, 101, 107, 109,
        110, 112, 114, 115, 118, 119, 120, 121, 122, 123, 127, 130, 135,
        136, 138, 140, 141, 143, 144, 148, 151, 153, 154, 155, 161, 164,
        166, 167, 168, 171, 172, 176, 177, 180, 181, 185, 186, 192, 194,
        200, 201, 205, 206, 208, 209, 213, 214, 216, 220, 221, 222, 223,
        225, 226, 228, 229, 230, 234, 239, 242, 244, 247, 249, 255, 258,
        259, 260, 262, 263, 264, 265, 266, 267, 268, 271, 272, 273, 281,
        282, 283, 291, 292, 293, 297, 302, 305, 308, 309, 312, 314, 315,
        322, 323, 329, 332, 333, 337, 341, 343, 344, 346, 347, 349, 350,
        352, 353, 354, 359, 363, 364, 371, 373, 374, 375, 376, 378, 382,
        383, 385, 389, 390, 394, 397, 399, 403, 407

In [14]:
print('Outlier Report')
mlcookbook.eda.outlier_report(data)

Outlier Report
Detecting outliers 

Single feature outlier tests
         IQR Z Score Percentile Multiple       IQR %   Z Score % Percentile %  \
CRIM      66       8          6        8    0.130435   0.0158103    0.0118577   
INDUS      0       0          3        0           0           0   0.00592885   
NOX        0       0          2        0           0           0   0.00395257   
RM        30       8          5        8   0.0592885   0.0158103   0.00988142   
AGE        0       0          3        0           0           0   0.00592885   
DIS        5       5          6        5  0.00988142  0.00988142    0.0118577   
TAX        0       0          1        0           0           0   0.00197628   
PTRATIO   15       0          5        0   0.0296443           0   0.00988142   
B         77      25          3       25    0.152174   0.0494071   0.00592885   
LSTAT      7       5          6        5    0.013834  0.00988142    0.0118577   
Target    40       0          3        0   0

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


{'Ellipses Envelope': (array([367, 373, 374, 375, 376, 378, 379, 380, 381, 384, 385, 386, 387,
         388, 392, 394, 398, 400, 401, 403, 404, 405, 406, 407, 409, 410,
         411, 412, 413, 414, 415, 416, 417, 418, 419, 422, 425, 426, 427,
         434, 435, 436, 437, 438, 440, 444, 445, 468, 469, 477, 479],
        dtype=int64),),
 'Isolation Forest': (array([  8,  48, 126, 141, 142, 143, 144, 145, 146, 147, 148, 149, 152,
         153, 155, 156, 159, 161, 162, 163, 166, 195, 197, 204, 214, 253,
         257, 258, 262, 267, 268, 283, 354, 355, 367, 368, 373, 374, 380,
         384, 410, 412, 414, 418, 419, 424, 426, 427, 438, 457, 490],
        dtype=int64),),
 'One Class SVM': (array([  0,   2,   3,   5,   6,   7,   9,  10,  12,  13,  15,  16,  17,
          20,  21,  22,  25,  30,  31,  32,  33,  34,  35,  38,  39,  41,
          42,  43,  44,  48,  49,  50,  51,  53,  54,  55,  56,  63,  68,
          73,  75,  76,  79,  81,  89,  93,  94,  97,  99, 101, 107, 109,
         110, 

## Preprocessing

In [15]:
print('PCA')
mlcookbook.process.fit_PCA(data)

PCA
Total variance % explained: 99.47547798971576

Variance % explained by principal component:
0 : 52.40359199401038
1 : 11.90709019180578
2 : 9.14680592105265
3 : 6.065593317676156
4 : 5.329659989504557
5 : 4.189201829407195
6 : 3.0784920531932687
7 : 2.4340904719387266
8 : 1.334769086567469
9 : 1.192136172161672
10 : 0.859088493451943
11 : 0.790408698079883
12 : 0.7445497708660539


array([[-0.56709519,  0.15613447,  0.01698635, ..., -0.13715014,
        -0.0358962 ,  0.04556913],
       [-0.42633164,  0.25114179, -0.18768805, ...,  0.04660025,
         0.00684545,  0.0536297 ],
       [-0.58068173,  0.143294  ,  0.00128317, ...,  0.06890589,
        -0.00825431, -0.0158398 ],
       ...,
       [-0.18116716,  0.39693602, -0.20295807, ..., -0.02189769,
        -0.05947226,  0.07618167],
       [-0.17393509,  0.38548429, -0.23495641, ..., -0.01993153,
        -0.04965579,  0.077509  ],
       [-0.14446137,  0.35112255, -0.37054574, ..., -0.05930353,
        -0.02947907,  0.14699223]])

In [19]:
print('Oversampling binary label')
mlcookbook.process.oversample_binary_label(categorical_data, 'Target')  # TODO: Fix this one

Oversampling Test
Initial number of observations in each class:
1    357
0    212
Name: Target, dtype: int64

Oversampled number of observations in each class:
1    357
0    212
Name: Target, dtype: int64


mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
19        13.540         14.36           87.46      566.3          0.09779   
20        13.080         15.71           85.63      520.0          0.10750   
21         9.504         12.44           60.34      273.9          0.10240   
37        13.030         18.42           82.61      523.8          0.08983   
46         8.196         16.84           51.71      201.9          0.08600   
48        12.050         14.63           78.04      449.3          0.10310   
49        13.490         22.30           86.91      561.0          0.08752   
50        11.760         21.60           74.72      427.9          0.08637   
51        13.640         16.34           87.21      571.8          0.07685   
52        11.940         18.24           75.71      437.6          0.08261   
55        11.520         18.75           73.34      409.0          0.09524   
58        13.050         19.31           82.61      527.2          0.08060   
59         8.618         11.79           54.34      224.5          0.09752   
60        10.170         14.88           64.55      311.9          0.11340   
61         8.598         20.98           54.66      221.8          0.12430   
63         9.173         13.86           59.20      260.9          0.07721   
66         9.465         21.01           60.11      269.4          0.10440   
67        11.310         19.04           71.80      394.1          0.08139   
68         9.029         17.33           58.79      250.5          0.10660   
69        12.780         16.49           81.37      502.5          0.09831   
71         8.888         14.64           58.79      244.0          0.09783   
74        12.310         16.52           79.19      470.9          0.09172   
76        13.530         10.94           87.91      559.2          0.12910   
79        12.860         18.00           83.19      506.3          0.09934   
80        11.450         20.97           73.81      401.5          0.11020   
81        13.340         15.86           86.49      520.0          0.10780   
84        12.000         15.65           76.95      443.3          0.09723   
88        12.360         21.80           79.78      466.1          0.08772   
89        14.640         15.24           95.77      651.9          0.11320   
90        14.620         24.02           94.57      662.7          0.08974   
..           ...           ...             ...        ...              ...   
435       13.980         19.62           91.12      599.5          0.10600   
563       20.920         25.09          143.00     1347.0          0.10990   
302       20.090         23.86          134.70     1247.0          0.10800   
64        12.680         23.84           82.69      499.0          0.11220   
263       15.610         19.38          100.00      758.6          0.07840   
498       18.490         17.52          121.30     1068.0          0.10120   
119       17.950         20.01          114.20      982.0          0.08402   
461       27.420         26.27          186.90     2501.0          0.10840   
57        14.710         21.59           95.55      656.9          0.11370   
514       15.050         19.07           97.26      701.9          0.09215   
521       24.630         21.60          165.50     1841.0          0.10300   
18        19.810         22.15          130.00     1260.0          0.09831   
330       16.030         15.51          105.80      793.2          0.09491   
302       20.090         23.86          134.70     1247.0          0.10800   
70        18.940         21.31          123.60     1130.0          0.09009   
3         11.420         20.38           77.58      386.1          0.14250   
161       19.190         15.94          126.30     1157.0          0.08694   
196       13.770         22.29           90.63      588.9          0.12000   
190       14.220         23.12           94.37      609.9          0.10750   
274       17.930         24

In [21]:
print('Oversampling with SMOTE Test')
# TODO: Fix this
# mlcookbook.process.fit_PCA(categorical_data.drop('Target', axis=1), categorical_data['Target'])

Oversampling with SMOTE Test


In [23]:
print('Target Mean Encoding')
# TODO: Fix this
mlcookbook.process.target_encode(data.drop('Target', axis=1), data.drop('Target', axis=1), data['Target'])

Target Mean Encoding


AttributeError: 'DataFrame' object has no attribute 'name'